-- Drop Table Parameter
DROP TABLE IF EXISTS `parameter`;

-- DDL Table Parameter
CREATE TABLE IF NOT EXISTS `parameter` (
  `id` int NOT NULL AUTO_INCREMENT,
  `parameter_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `group` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `has_prediction` tinyint(1) NOT NULL DEFAULT '0',
  `input_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `field_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `input_options` varchar(1500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hint_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hint_en` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sub_group` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `time_classification` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `notes` varchar(1023) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `priority` int NOT NULL DEFAULT '0',
  `source` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unit` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `optional_units` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_name_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_name_en` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `export_header_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `y_range_min` float DEFAULT NULL,
  `y_range_max` float DEFAULT NULL,
  `x_range_min` float DEFAULT NULL,
  `x_range_max` float DEFAULT NULL,
  `x_legend` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `threshold_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'minimal, maximal, between',
  `threshold_min` float DEFAULT NULL,
  `threshold_max` float DEFAULT NULL,
  `extreme_changes_lower` int DEFAULT NULL COMMENT 'extreme changes lower value in percentages',
  `extreme_changes_upper` int DEFAULT NULL COMMENT 'extreme changes upper value in percentages',
  `alert_tracking_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `alert_threshold_min` float NOT NULL DEFAULT '0',
  `alert_threshold_max` float NOT NULL DEFAULT '0',
  `alert_difference` float NOT NULL DEFAULT '0',
  `graph_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `metrics_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `data_level` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `json_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `table_column_key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `table_source` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `additional_config` varchar(1023) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_params` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` smallint NOT NULL DEFAULT '1',
  `flag` int NOT NULL DEFAULT '0',
  `meta` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `parameter_index` (`group`,`time_classification`,`source`)
) ENGINE=InnoDB AUTO_INCREMENT=1028 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Drop Table Parameter Column Index
DROP TABLE IF EXISTS `parameter_column_index`;

-- DDL Table Parameter Column Index
CREATE TABLE IF NOT EXISTS `parameter_column_index` (
  `id` int NOT NULL AUTO_INCREMENT,
  `parameter_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `number_format` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_general_column` tinyint(1) NOT NULL DEFAULT '0',
  `is_constant` tinyint(1) NOT NULL DEFAULT '0',
  `col_index` int NOT NULL DEFAULT '0',
  `sheet_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `formula` varchar(1020) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Formula for Parameter Column Index',
  `dropdown` varchar(1020) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_zero_allowed` tinyint(1) DEFAULT '0',
  `status` smallint NOT NULL DEFAULT '1',
  `flag` int NOT NULL DEFAULT '0',
  `meta` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=476 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;