
-- Drop Table Pond
DROP TABLE IF EXISTS `pond`;

-- Create Table Pond
CREATE TABLE IF NOT EXISTS `pond` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fk_farm_id` int NOT NULL,
  `fk_module_id` int NOT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `code` varchar(255) NOT NULL DEFAULT '',
  `pond_type` int NOT NULL DEFAULT '0',
  `area_m2` float DEFAULT NULL,
  `depth_m` float DEFAULT NULL,
  `length_m` float DEFAULT NULL,
  `width_m` float DEFAULT NULL,
  `latest_metric_date` date DEFAULT NULL,
  `latest_sampling_date` date DEFAULT NULL,
  `current_wqi_score` float DEFAULT NULL,
  `current_fk_cycle_id` int DEFAULT NULL,
  `current_cycle_name` varchar(255) DEFAULT NULL,
  `current_cycle_status` varchar(255) DEFAULT NULL,
  `is_final_harvest` tinyint(1) DEFAULT NULL,
  `current_cycle_severity` varchar(255) DEFAULT NULL,
  `current_cycle_severity_rating` float DEFAULT NULL,
  `current_cycle_dop_start_date` date DEFAULT NULL,
  `current_cycle_dop_end_date` date DEFAULT NULL,
  `current_cycle_doc_start_date` date DEFAULT NULL,
  `current_cycle_doc_end_date` date DEFAULT NULL,
  `current_cycle_hatchery` varchar(255) DEFAULT NULL,
  `current_cycle_stocking_date` date DEFAULT NULL,
  `current_cycle_stocking_netto` int DEFAULT NULL,
  `current_cycle_stocking_gross` int DEFAULT NULL,
  `current_cycle_stocking_actual` int DEFAULT NULL,
  `current_cycle_density_netto` int DEFAULT NULL,
  `current_cycle_density_gross` int DEFAULT NULL,
  `current_cycle_density_actual` int DEFAULT NULL,
  `current_cycle_acc_feed` float DEFAULT NULL,
  `current_cycle_sampling` int NOT NULL DEFAULT '1',
  `harvest_plan_min_shrimp_size` int unsigned DEFAULT '60',
  `harvest_plan_max_shrimp_size` int unsigned DEFAULT '100',
  `harvest_plan_day_interval` int unsigned DEFAULT '5',
  `harvest_plan_doc_length` int unsigned DEFAULT '120',
  `harvest_plan_biomass_target` int unsigned DEFAULT '500',
  `disease_description` varchar(255) DEFAULT NULL,
  `status` smallint NOT NULL DEFAULT '1',
  `flag` int NOT NULL DEFAULT '0',
  `meta` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(255) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` varchar(255) DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1616 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;